name: Auto deploy Gitbook

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v1

      - name: Setting Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Gitbook CLI and plugins
        run: |
          export TZ='Asia/Shanghai'
          npm install gitbook-cli -g
          gitbook install

      - name: Build Gitbook
        run: |
          gitbook build

      - name: Deploy To Coding.net
        run: |
          cd ./_book
          git init
          git config user.name "${{secrets.GIT_NAME}}"
          git config user.email "${{secrets.GIT_EMAIL}}"
          git add -A
          git commit -m "Update"
          git push --force "https://${{secrets.CD_TOKEN}}@${{secrets.CD_REF}}" master:master
        # CD_Token: "coding_user:coding_token" , CD_REF: "repo addr"
